### ISSUE TITLE
Review CSV-W

### ISSUE THREAD

**Issue by abdulkasim1** [GSS-Cogs/provider-met-office#2]
Review the MetOffice provided CSV-W at https://github.com/GSS-Cogs/provider-met-office to ensure it matches our standards.

**Comment by abdulkasim1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Data-Science-62e1271e6637230015993435/issues/GSS-Cogs/provider-met-office/2?planning-poker) with Zenhub @sazzadur-ons @BenHowland @FemShow

**Comment by abdulkasim1** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Data-Science-62e1271e6637230015993435/issues/GSS-Cogs/provider-met-office/2?planning-poker) with Zenhub @abdulkasim1

**Comment by GregoryJPavier** [comment]
**Feedback for the CSVW**

- Change the observation data type from float to decimal. Decimal offers a more reliable, accurate representation of values.

- For the data itself; Remove 'Annual' from the measure column values, so it's just 'Mean Temperature', since it's already explicit that these values are for their respective years.

- [Define the measures](https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/qube-config/measure-definitions/#description). Give more detail as to what 'Mean Temperature' and 'Mean Temperature (Trend)' are/mean.
